### ISSUE TITLE
Provide logo raw assets

### ISSUE THREAD

**Issue by grahamsmith** [nottsjs/resources#1]
Provide raw assets for logo and other resources

**Comment by iancrowther** [comment]
@joemckie can you commit these?

**Comment by joemckie** [comment]
Raw assets as in the PSD?

**Comment by grahamsmith** [comment]
Yes and any other raw files (fonts etc)

**Comment by joemckie** [comment]
Sure, will do it when I'm in the office. Might not be till after NY now though, if that's alright

**Comment by iancrowther** [comment]
tbh joe, now would be better

**Comment by joemckie** [comment]
Sure, it's on my desktop in the office, though, and I don't think I'll be home again until after the new year. I can recreate it on my laptop tonight if it's urgent.

**Comment by iancrowther** [comment]
ah i see, sorry thought you were at home

**Comment by joemckie** [comment]
No worries - only took a second anyway. Just pushed that in
